In [3]:
# Cell 1
import pandas as pd
import pyarrow.parquet as pq
!pip install duckdb

zsh:1: /Users/gabrieltang/Documents/Uni Stuffs/nussifPortfolioRisk/venv/bin/pip: bad interpreter: /home/ubuntu/app/venv/bin/python3: no such file or directory
Requirement already satisfied: duckdb in /opt/anaconda3/lib/python3.13/site-packages (1.4.4)

In [ ]:
# Cell 2 - Read with DuckDB
import duckdb

nav_df = duckdb.sql("SELECT * FROM 'nav.parquet'").df()
nav_df.head()

                       date         nav    unrealised
0 2025-12-27 15:00:00+08:00  1035043.51  39734.188747
1 2025-12-27 18:00:00+08:00  1035043.51  39734.188747
2 2025-12-27 23:00:00+08:00  1035043.51  39734.188747
3 2025-12-28 01:00:00+08:00  1035043.51  39734.188747
4 2025-12-28 01:00:00+08:00  1035043.51  39734.188747

In [ ]:
# pnl.parquet is derived from nav.parquet
pnl_df = duckdb.sql("SELECT * FROM 'pnl.parquet'").df()
pnl_df.head()

,date,nav,unrealisedPnL,totalPnL,realisedPnL,percentage_change
0,2025-12-27 15:00:00+08:00,1035043.51,39734.19,35043.51,-4690.68,3.5
1,2025-12-27 18:00:00+08:00,1035043.51,39734.19,35043.51,-4690.68,3.5
2,2025-12-27 23:00:00+08:00,1035043.51,39734.19,35043.51,-4690.68,3.5
3,2025-12-28 01:00:00+08:00,1035043.51,39734.19,35043.51,-4690.68,3.5
4,2025-12-28 01:00:00+08:00,1035043.51,39734.19,35043.51,-4690.68,3.5

In [ ]:
# global_avg_metric.parquet
global_avg_metric_df = duckdb.sql("SELECT * FROM 'global_avg_metric.parquet'").df()
global_avg_metric_df.head()

,date,avgVar99_1d,avgEs99_1d,avgVar99_5d,avgEs99_5d,avgVar99_21d,avgEs99_21d,avgVar95_1d,avgEs95_1d,avgVar95_5d,avgEs95_5d,avgVar95_21d,avgEs95_21d,avgVar90_1d,avgEs90_1d,avgVar90_5d,avgEs90_5d,avgVar90_21d,avgEs90_21d
0,2025-12-02 03:00:00+08:00,8862.030,12071.815,18568.235,23639.140,35942.650,40807.860,5710.235,7801.21,11797.410,16166.670,24049.075,31453.005,4191.710,6346.390,8854.820,13174.060,17705.790,26024.83
1,2025-12-02 04:00:00+08:00,8924.760,12080.285,18789.870,23798.300,36001.375,40871.905,5780.130,7844.07,11948.875,16280.340,24258.565,31599.920,4231.225,6385.010,8932.490,13287.610,17678.215,26137.60
2,2025-12-02 05:00:00+08:00,8954.885,12181.495,18870.200,24014.255,36147.125,40885.380,5761.205,7882.16,11942.775,16347.245,24378.525,31630.865,4225.615,6403.260,8881.540,13294.900,17629.575,26162.75
3,2025-12-02 06:00:00+08:00,8930.315,12177.725,18960.150,24039.545,36102.270,41046.605,5773.925,7879.78,11961.575,16368.795,24146.705,31540.085,4254.645,6411.445,8918.385,13331.845,17512.710,26013.65
4,2025-12-02 07:00:00+08:00,8957.835,12191.380,18857.430,23920.560,36242.925,41149.750,5771.190,7891.79,11909.925,16304.975,24359.570,31727.280,4251.795,6412.775,8904.915,13292.380,17676.215,26204.02

In [10]:
# weights.parquet
weights_df = duckdb.sql("SELECT * FROM 'weights.parquet'").df()
weights_df.head()

  symbol   weights                      date
0   TFLO  0.128186 2025-12-02 03:00:00+08:00
1    VEA  0.035700 2025-12-02 03:00:00+08:00
2    VXZ  0.224921 2025-12-02 03:00:00+08:00
3    IEF  0.098792 2025-12-02 03:00:00+08:00
4    GLD  0.074252 2025-12-02 03:00:00+08:00

In [8]:
# vol.parquet
vol_df = duckdb.sql("SELECT * FROM 'vol.parquet'").df()
vol_df.head()

  symbol  volatility                      date
0   TFLO    0.004157 2025-12-02 03:00:00+08:00
1    VEA    0.010987 2025-12-02 03:00:00+08:00
2    VXZ    0.019976 2025-12-02 03:00:00+08:00
3    IEF    0.005060 2025-12-02 03:00:00+08:00
4    GLD    0.008565 2025-12-02 03:00:00+08:00

In [12]:
# corr.parquet
corr_df = duckdb.sql("SELECT * FROM 'corr.parquet'").df()
corr_df.head()

  asset1 asset2      corr                      date
0    G3B    G3B  1.000000 2026-01-30 00:00:00+08:00
1    G3B    ES3  0.881567 2026-01-30 00:00:00+08:00
2    ES3    G3B  0.881567 2026-01-30 00:00:00+08:00
3    ES3    ES3  1.000000 2026-01-30 00:00:00+08:00

In [13]:
# stopLossTracker.parquet
stopLossTracker_df = duckdb.sql("SELECT * FROM 'stopLossTracker.parquet'").df()
stopLossTracker_df.head()

                       date         nav
0 2026-01-04 22:00:00+08:00  1034169.77
1 2026-01-05 00:00:00+08:00  1034169.77
2 2026-01-05 01:00:00+08:00  1034169.77
3 2026-01-05 01:00:00+08:00  1034169.77
4 2026-01-05 01:17:00+08:00  1034169.77